from enum import Enum


class Key(Enum):
    @staticmethod
    def of(c):
        return next((member for name, member in Key.__members__.items() if str(c) in member.value), None)

    OF_1 = '1!'
    OF_2 = '2@'
    OF_3 = '3#'
    OF_4 = '4$'
    OF_5 = '5%'
    OF_6 = '6^'
    OF_7 = '7&'
    OF_8 = '8*'
    OF_9 = '9('
    OF_0 = '0)'
    OF_A = 'aA'
    OF_B = 'bB'
    OF_C = 'cC'
    OF_D = 'dD'
    OF_E = 'eE'
    OF_F = 'fF'
    OF_G = 'gG'
    OF_H = 'hH'
    OF_I = 'iI'
    OF_J = 'jJ'
    OF_K = 'kK'
    OF_L = 'lL'
    OF_M = 'mM'
    OF_N = 'nN'
    OF_O = 'oO'
    OF_P = 'pP'
    OF_Q = 'qQ'
    OF_R = 'rR'
    OF_S = 'sS'
    OF_T = 'tT'
    OF_U = 'uU'
    OF_V = 'vV'
    OF_W = 'wW'
    OF_X = 'xX'
    OF_Y = 'yY'
    OF_Z = 'zZ'
    OF_SEMICOLON = ';:'
    OF_COMMA = ',<'
    OF_PERIOD = '.>'
    OF_OPENING_BRACKET = '[{'
    OF_CLOSING_BRACKET = ']}'
    OF_HYPHEN = '-_'
    OF_EQUAL = '=+'
    OF_SLASH = '/?'
    OF_BACK_SLASH = '\\|'
    OF_QUOTE = '\'"'
    OF_BACK_QUOTE = '`~'
