from key import Key


def show_keymap(keymap):
    str_map = list(map(lambda k: k.value[0], keymap))
    print(('| ' + ' | '.join(str_map[:13]) + ' |').upper())
    print(('     | ' + ' | '.join(str_map[13:26]) + ' |').upper())
    print(('      | ' + ' | '.join(str_map[26:37]) + ' |').upper())
    print(('       | ' + ' | '.join(str_map[37:]) + ' |').upper())


QWERTY = [
    Key.OF_BACK_QUOTE,
    Key.OF_1,
    Key.OF_2,
    Key.OF_3,
    Key.OF_4,
    Key.OF_5,
    Key.OF_6,
    Key.OF_7,
    Key.OF_8,
    Key.OF_9,
    Key.OF_0,
    Key.OF_HYPHEN,
    Key.OF_EQUAL,
    Key.OF_Q,
    Key.OF_W,
    Key.OF_E,
    Key.OF_R,
    Key.OF_T,
    Key.OF_Y,
    Key.OF_U,
    Key.OF_I,
    Key.OF_O,
    Key.OF_P,
    Key.OF_OPENING_BRACKET,
    Key.OF_CLOSING_BRACKET,
    Key.OF_BACK_SLASH,
    Key.OF_A,
    Key.OF_S,
    Key.OF_D,
    Key.OF_F,
    Key.OF_G,
    Key.OF_H,
    Key.OF_J,
    Key.OF_K,
    Key.OF_L,
    Key.OF_SEMICOLON,
    Key.OF_QUOTE,
    Key.OF_Z,
    Key.OF_X,
    Key.OF_C,
    Key.OF_V,
    Key.OF_B,
    Key.OF_N,
    Key.OF_M,
    Key.OF_COMMA,
    Key.OF_PERIOD,
    Key.OF_SLASH,
]

DVORAK = [
    Key.OF_BACK_QUOTE,
    Key.OF_1,
    Key.OF_2,
    Key.OF_3,
    Key.OF_4,
    Key.OF_5,
    Key.OF_6,
    Key.OF_7,
    Key.OF_8,
    Key.OF_9,
    Key.OF_0,
    Key.OF_OPENING_BRACKET,
    Key.OF_CLOSING_BRACKET,
    Key.OF_QUOTE,
    Key.OF_COMMA,
    Key.OF_PERIOD,
    Key.OF_P,
    Key.OF_Y,
    Key.OF_F,
    Key.OF_G,
    Key.OF_C,
    Key.OF_R,
    Key.OF_L,
    Key.OF_SLASH,
    Key.OF_EQUAL,
    Key.OF_BACK_SLASH,
    Key.OF_A,
    Key.OF_O,
    Key.OF_E,
    Key.OF_U,
    Key.OF_I,
    Key.OF_D,
    Key.OF_H,
    Key.OF_T,
    Key.OF_N,
    Key.OF_S,
    Key.OF_HYPHEN,
    Key.OF_SEMICOLON,
    Key.OF_Q,
    Key.OF_J,
    Key.OF_K,
    Key.OF_X,
    Key.OF_B,
    Key.OF_M,
    Key.OF_W,
    Key.OF_V,
    Key.OF_Z,
]

NORMAN = [
    Key.OF_BACK_QUOTE,
    Key.OF_1,
    Key.OF_2,
    Key.OF_3,
    Key.OF_4,
    Key.OF_5,
    Key.OF_6,
    Key.OF_7,
    Key.OF_8,
    Key.OF_9,
    Key.OF_0,
    Key.OF_HYPHEN,
    Key.OF_EQUAL,
    Key.OF_Q,
    Key.OF_W,
    Key.OF_D,
    Key.OF_F,
    Key.OF_K,
    Key.OF_J,
    Key.OF_U,
    Key.OF_R,
    Key.OF_L,
    Key.OF_SEMICOLON,
    Key.OF_OPENING_BRACKET,
    Key.OF_CLOSING_BRACKET,
    Key.OF_BACK_SLASH,
    Key.OF_A,
    Key.OF_S,
    Key.OF_E,
    Key.OF_T,
    Key.OF_G,
    Key.OF_Y,
    Key.OF_N,
    Key.OF_I,
    Key.OF_O,
    Key.OF_H,
    Key.OF_QUOTE,
    Key.OF_Z,
    Key.OF_X,
    Key.OF_C,
    Key.OF_V,
    Key.OF_B,
    Key.OF_P,
    Key.OF_M,
    Key.OF_COMMA,
    Key.OF_PERIOD,
    Key.OF_SLASH,
]
